name: Deploy Valentine Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .   # ensures package.json is found in repo root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug directory contents
        run: |
          echo "Working dir: $PWD"
          ls -R .

      - name: Install dependencies
        run: npm install

      - name: Build site (if needed)
        run: npm run build || echo "no build needed"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /var/www/valentine-site
            git pull origin main
            npm install || true
            pm2 restart valentine-site || pm2 start index.html --name valentine
          EOF

